image: maven:3-jdk-8
before_script:
 - source ./env-properties.sh
stages:
 - test
 - build
services:
 - 'mysql:latest'
variables:
 MYSQL_DATABASE: moviedb
 MYSQL_CI_URL: jdbc:mysql://mysql/moviedb
 MYSQL_USER: root
 MYSQL_ROOT_PASSWORD: root
cache:
 paths:
   - .m2/repository/
   - target
maven-test:
 stage: test
 script: 'mvn test -B'
maven-build:
 stage: build
 script: 'mvn package -U'
 artifacts:
  paths:
    - 'target/*.jar'
