image: 'maven:3-jdk-8'
stages:
 - test
 - build
services:
 - 'mysql:5.5'
variables:
 MYSQL_DATABASE: movieDb
 MYSQL_CI_URL: jdbc:mysql://mysql/movieDb
 MYSQL_USER: app-root
 MYSQL_ROOT_PASSWORD: root123
 MYSQL_PASSWORD: root123
cache:
 paths:
  - .m2/repository/
  - target
maven-test:
 stage: test
 script: "mvn test -B"
maven-build:
 stage: build
 script: "mvn package -U"  
 artifacts:
  paths:
   - target/*.jar
