version: '2'
services: 
  user-app:
    image: mc-usersvc
    build: MovieServices/
    restart: always
    network_mode: host
    ports:
     - '8081:8081'
    expose:
     - 8081
    depends_on:
     - mc-mysql
  movie-app:
    image: mc-moviesvc
    build: UserServices/
    restart: always
    network_mode: host
    ports:
      - '8080:8080'
    expose:
      - 8080
    depends_on:
      - mc-mysql
  mc-mysql:
    image: 'mysql:latest'
    restart: always
    network_mode: host
    expose:
      - 3306
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: root123
      MYSQL_USER: root
      MYSQL_PASSWORD: root123
      MYSQL_DATABASE: movieDb
  mc-frontend:
    image: 'mc-frontend'
    restart: always
    network_mode: host
    expose:
      - 4200
    ports:
      - '4200:4200'   
